Collect metrics for the `ic-canister`-derived canisters
infinity-swap/ic-helpers pull request #56
Opened 2022-05-27 13:09 UTC by awkure

2022-05-30 06:42 UTC, hagsteel requested changes
I think perhaps the interval idents should really be:
* every-minute
* hourly
* daily
* weekly
* monthly
or something to that avail.
Let's discuss this in chat

2022-05-30 06:42 UTC, hagsteel commented on ic-canister/ic-canister-macros/src/derive.rs
> +                    .or_insert(new_metrics);
```suggestion
                metrics.insert(new_ts, new_metrics);
```

2022-05-30 06:42 UTC, hagsteel commented on ic-canister/ic-canister/src/lib.rs
> +//! Metrics for the canister can be collected by adding `#[metrics]` field to the canister struct.
```suggestion
//! Metrics for the canister can be collected by adding a `#[metrics]` field to the canister struct.
```

2022-05-30 06:42 UTC, hagsteel commented on ic-canister/ic-canister/src/lib.rs
> +//! Note that `Metrics` is wrapped under the [`MetricsMap`] struct. This is an implementation
```suggestion
//! Note that `Metrics` is wrapped inside the [`MetricsMap`] struct. This is an implementation
```

2022-05-30 06:42 UTC, hagsteel commented on ic-canister/ic-canister/src/lib.rs
> +//! detail used storing the metrics properly.
```suggestion
//! detail used for storing the metrics properly.
```

2022-05-30 06:42 UTC, hagsteel commented on ic-canister/ic-canister/src/lib.rs
> +//! Under the hood this adds two calls to the `MyCanister` that utilitzes `metrics` state: `collect_metrics()` and `get_metrics()`.
```suggestion
//! Under the hood this adds two calls to the `MyCanister` struct that utilizes `metrics` state: `collect_metrics()` and `get_metrics()`.
```

2022-05-30 06:42 UTC, hagsteel commented on ic-canister/ic-canister/src/lib.rs
> +//! With that in place we need to set up the logic for metrics calculation. This is done by setting
```suggestion
//! With that in place we need to set up the logic for metrics calculation. This is done by setting the
```

2022-05-30 06:42 UTC, hagsteel commented on ic-canister/ic-canister/src/lib.rs
> +//! `new_metric_snapshot` query method (that will ask you to set up if it's not yet present).
```suggestion
//! `new_metric_snapshot` query method (see example below)
```

2022-05-30 06:42 UTC, hagsteel commented on ic-canister/ic-canister/src/lib.rs
> +//! a number of minutes or an ident from the list `[min, hour, day, week, month]`.
```suggestion
//! You can specify an interval for metrics collection by setting it explicitly (by default it collects
//! metrics every day) via `#[metrics(interval = interval_value)]` where `interval_value` is either
//! the number of minutes or an ident from the list `[min, hour, day, week, month]`.
```

2022-05-30 06:42 UTC, hagsteel commented on ic-canister/ic-canister/src/lib.rs
> +//! For an example you can refer to the tests in `canister_b` crate.
```suggestion
//! For an example you can refer to the tests in the `canister_b` crate.
```

2022-05-30 07:12 UTC, hagsteel commented on ic-canister/ic-canister-macros/src/derive.rs
> +            "month" => Interval { mins: 60 * 24 * 30 },
Also update anywhere in the docs / examples where this is used
```suggestion
            "hourly" => Interval { mins: 60 },
            "daily" => Interval { mins: 60 * 24 },
            "weekly" => Interval { mins: 60 * 24 * 7 },
            "monthly" => Interval { mins: 60 * 24 * 30 },
```

2022-05-30 08:03 UTC, hagsteel approved these changes
Looks good!

2022-05-31 07:06 UTC, Maximkaaa reviewed
I'd rather we go with the trait approach:
```
pub trait MetricsCanister : Canister {
  ...
}
```

2022-06-03 09:33 UTC, awkure commented
Closing in favor https://github.com/infinity-swap/ic-helpers/pull/58

2022-06-03 09:33 UTC, closed without merging