[CPROD-846] Collect metrics for the ic canisters
infinity-swap/ic-helpers pull request #58
Opened 2022-05-31 09:02 UTC by awkure

This is the same as https://github.com/infinity-swap/ic-helpers/pull/56 but without using deriving macros

2022-06-03 11:03 UTC, Maximkaaa requested changes
It seems to me that in this form the `Metrics` are not really related to `ic-canister`, so it's a little strange to have documentation for them in that crate. Why don't we move the docs to the `MetricMap` struct.

It's probably fine to test this in `CanisterA`/`CanisterB`, though the test you wrote should rather be just a simple unit test for that struct. That would be cleaner. But if you leave it as is, I won't mind too much.

2022-06-06 06:36 UTC, Maximkaaa commented
I don't think it's a good approach for docs. We don't put factory docs, ledger and management API docs in here because there is more appropriate places for them. Same goes with metrics.

2022-06-10 07:15 UTC, Maximkaaa approved these changes

2022-06-10 18:44 UTC, AlessandroRiet approved these changes

2022-06-10 18:44 UTC, merged